"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/Navbar";
import { ThemeContextProvider } from "@/context/ThemeContext";
import ThemeProvider from "@/providers/ThemeProvider";
import React from "react";
import { QueryClientProvider } from 'react-query';
import queryClient from '../queryClient'; 

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
        <ThemeContextProvider>
          <ThemeProvider>
            <Navbar/>
            {children}
            <Footer />
          </ThemeProvider>
        </ThemeContextProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
